api/urls.py
from django.conf.urls import include, url

from rest_framework import routers

from . import views

router = routers.DefaultRouter()

router.register(r'projects', views.ProjectsViewSet, base_name='projects')

urlpatterns = [
    url(r'^', include(router.urls))
]

app/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^', include('web.urls', namespace='web')),
    url(r'^', include('projects.urls', namespace='projects')),
    url(r'^admin/', admin.site.urls),
]

projects/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^client-autocomplete/$', views.ClientAutocomplete.as_view(),
        name='client-autocomplete'),
]

web/urls.py
from django.conf.urls import url

from web.views.home import HomeView
from web.views.logout import LogoutView
from web.views.project import ProjectView


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^logout$', LogoutView.as_view(), name='logout'),
    url(r'^p/(?P<pk>[\w/\-]+)?$', ProjectView.as_view(), name='project'),
]

projects/models.py
from functools import reduce
from operator import or_

from django.db import models
from django.db.models import Q


class ModelBase(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Client(models.Model):
    department = models.CharField(
        help_text='Deparment is the highest organizational level.',
        max_length=255,
        blank=True
    )
    agency = models.CharField(
        help_text='Agency is the level below the Department.',
        max_length=255,
        blank=True
    )
    omb_agency_code = models.CharField(
        help_text='OMB Agency Code is the top level code.',
        max_length=255,
        blank=True,
        verbose_name='OMB Agency Code'
    )
    omb_bureau_code = models.CharField(
        help_text='OMB Bureau Code is the level below OMB Agency Code.',
        max_length=255,
        blank=True,
        verbose_name='OMB Bureau Code'
    )
    treasury_agency_code = models.CharField(
        max_length=255,
        blank=True,
        verbose_name='Treasury Agency Code'
    )
    cgac_agency_code = models.CharField(
        max_length=255,
        blank=True,
        verbose_name='CGAC Agency Code'
    )

    class Meta:
        ordering = ['department', 'agency']

    def __str__(self):
        return '%s - %s' % (self.department, self.agency)


class BusinessUnit(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class ProjectManager(models.Manager):
    def search(self, terms):
        qs = self.get_queryset()
        terms = [term.strip() for term in terms.split()]

        if not terms:
            return qs

        q_objs = []
        for term in terms:
            q_objs.append(Q(name__icontains=term))
            q_objs.append(Q(tagline__icontains=term))

        return qs.filter(reduce(or_, q_objs))


class Project(ModelBase):
    name = models.CharField(
        max_length=100,
        help_text='The full name of the project (e.g., "Agile BPA")'
    )
    slug = models.CharField(
        max_length=100,
        help_text='The slug of the project (e.g., "agile-bpa")',
        blank=True
    )
    tagline = models.CharField(
        max_length=300,
        help_text='The tagline of the project; short and concise.',
        blank=True
    )
    client = models.ForeignKey(
        Client,
        help_text='The client of the project, if any.',
        blank=True,
        null=True
    )
    project_lead = models.CharField(
        help_text='Name of 18F employee who is responsible for this'
        ' project.',
        max_length=255,
        verbose_name='Project Lead',
        blank=True
    )
    description = models.TextField(
        help_text='The description of the project. Markdown is allowed.'
    )
    impact = models.TextField(
        help_text='The impact of the project. Markdown is allowed.',
        blank=True
    )
    live_site_url = models.URLField(
        help_text='A URL to the site where the project is deployed, '
                  'if one exists.',
        blank=True,
        verbose_name='Live URL'
    )
    github_url = models.URLField(
        help_text='The GitHub URL of the project, e.g. '
                  'https://github.com/18f/agile-bpa',
        blank=True,
        verbose_name='GitHub URL'
    )
    status = models.IntegerField(
        help_text='Current status of the project.',
        choices=[
            (0, 'Tentative'), (1, 'Active'), (2, 'Paused'), (3, 'Complete')
        ],
        default=1
    )
    is_billable = models.BooleanField(
        help_text='Whether or not the project is chargeable to a'
        ' non-18F client.',
        default=False
    )
    cloud_dot_gov = models.BooleanField(
        help_text='Whether or not the project includes cloud.gov '
        'platform support.',
        default=False,
        verbose_name='Cloud.gov Project'
    )
    tock_id = models.IntegerField(
        help_text='The ID of the project in Tock.',
        blank=True,
        null=True,
        unique=True,
        verbose_name='Tock ID'
    )
    mb_number = models.CharField(
        help_text='The unique identifier for an agreement in'
        'the GSA financial system. This is different than'
        'the Tock ID.',
        max_length=100,
        blank=True,
        verbose_name='MB Number'
    )
    business_unit = models.ForeignKey(
        BusinessUnit,
        help_text='The Business Unit that owns the project.',
        default=None,
        blank=True,
        null=True,
        verbose_name='Business Unit'
    )
    is_visible = models.BooleanField(
        help_text='Projects with a primary private repos should'
        'be listed as false. All other projects should be '
        'listed as true.',
        default=False,
        verbose_name='Is visible (in dashboard)?'
    )

    objects = ProjectManager()

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

projects/forms.py
from dal import autocomplete

from django import forms
from .models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project

        fields = ('__all__')

        widgets = {
            'client': autocomplete.ModelSelect2(
              url='projects:client-autocomplete'
            )
        }

projects/views.py
from django.db.models import Q
from dal import autocomplete

from .models import Client


class ClientAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        user = self.request.user

        if not (user.is_authenticated() and user.is_staff):
            return Client.objects.none()

        qs = Client.objects.all()

        if self.q:
            qs = qs.filter(
                Q(department__icontains=self.q) |
                Q(agency__icontains=self.q)
            )

        return qs

web/views/project.py
from django.views.generic.detail import DetailView

from projects.models import Project


class ProjectView(DetailView):
    context_object_name = 'project'
    model = Project
    template_name = 'web/project.html'

web/templates/web/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Projects{% endblock %}</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link href="//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet">
  <link href="/static/build/main.css" rel="stylesheet">
</head>
<body>
  <div class="h6 p1 bg-black white center caps">Work in Progress</div>
  <div class="container px2 py3">
    <div class="mb4">
      <div class="right">
        {% if request.user.is_authenticated %}
        {{ request.user }} <a href="{% url 'web:logout' %}">Logout</a>
        {% else %}
        <a href="{% url 'social:begin' 'github-org' %}?next={{ request.path }}">Login with Github</a>
        {% endif %}
      </div>
      <a href="/" class="h1 p0 btn">
        <img src="/static/img/logo.png" class="align-middle" width="75">
        <span class="bold gray">/projects</span>
      </a>
    </div>
    {% block content %}{% endblock %}
  </div>
</body>
</html>

web/templates/web/index.html
{% extends 'web/base.html' %}


{% block content %}
<h1>Here are some cool things we helped build</h1>
<form class="py2">
  <label class="hide" for="search">Search</label>
  <input type="text" class="field" name="q" value="{{ query }}" placeholder="Search">
  <button class="btn btn-outline bg-white">Search</button>
</form>
<div class="flex flex-wrap mxn2">
{% for p in projects %}
  <div class="col-12 sm-col-6 md-col-4 border-box p2">
    <div class="p2 bg-white border rounded">
      <a class="h4 caps bold mb1 block black" href="{% url 'web:project' p.pk %}">
        <span class="right"><i class="icon ion-help-circled"></i></span>
        {{ p.name }}
      </a>
      <div class="mb2">
        {{ p.tagline }}
      </div>
      {% if p.client %}
      <div class="h6 mb2">
        Developed with <span class="bold underline">{{ p.client.agency }}</span>
      </div>
      {% endif %}
      <div class="h3">
        {% if p.live_site_url %}
        <a href="{{ p.live_site_url }}" class="black"><i class="icon ion-share"></i></a>&nbsp;
        {% endif %}
        {% if p.github_url %}
        <a target="_blank" href="{{ p.github_url }}" class="black"><i class="icon ion-code-working"></i></a>
        {% endif %}
      </div>
    </div>
  </div>
{% endfor %}
</div>
{% endblock %}

web/templates/web/project.html
{% extends 'web/base.html' %}


{% block content %}
<h1>{{ project.name }}</h1>
<p>{{ project.description }}</p>
{% endblock %}